# Project information
site_name: "ASTREA"
site_description: "An extensible astrodynamics library for C++"
site_url: https://iulianojay.github.io/astrea
site_author: "Jay Iuliano"

# Repository
repo_name: iulianojay/astrea
repo_url: https://github.com/iulianojay/astrea

# Copyright
copyright: Copyright &copy; 2025-2026 Jay Iuliano

# Configuration
theme:
  name: material
  logo: assets/images/astrea-transparent-crop.png
  favicon: assets/images/astrea-transparent-crop.png
  custom_dir: docs/.overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - navigation.expand
    - navigation.indexes
    # - navigation.sections
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/ce_embed.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
  - Getting Started:
      - Getting Started: getting_started/index.md
      - About Astrea: getting_started/about.md
      - Project Structure: getting_started/project_structure.md
      - Installation and Usage: getting_started/installation_and_usage.md
      - Contributing: getting_started/contributing.md
  - Examples:
      - Examples: examples/index.md
      - Tags: examples/tags.md
      - Fundamentals:
          - Strongly Typed Units: examples/fundamentals/strongly_typed_units.md
          - Strongly Typed Frames: examples/fundamentals/strongly_typed_frames.md
          - Time Systems: examples/fundamentals/time_systems.md
          - State Representations: examples/fundamentals/state_representations.md
          - Astrodynamic Systems: examples/fundamentals/astrodynamic_systems.md
          - Propagation:
            - Numerical Integration: examples/fundamentals/propagation/numerical_integration.md
            - Lambert Solutions: examples/fundamentals/propagation/lambert_solutions.md
            - Equations of Motion: examples/fundamentals/propagation/equations_of_motion.md
            - Force Models: examples/fundamentals/propagation/force_models.md
            - Events: examples/fundamentals/propagation/events.md
          - Frames:
            - Strongly Typed Frames: examples/fundamentals/frames/strongly_typed_frames.md
            - Frame Transformations: examples/fundamentals/frames/frame_transformations.md
            - Cartesian Vectors: examples/fundamentals/frames/cartesian_vectors.md
      - Advanced:
          - Vehicles: examples/advanced/vehicles.md
          - Platforms and Payloads: examples/advanced/platforms_and_payloads.md
  - Tutorials:
      - Tutorials: tutorials/index.md
  - Validation:
      - Validation: validation/index.md
      - Checkcases: validation/checkcases.md
  - Design:
      - Design: design/index.md
      - Type System: design/type_system.md
      - Architecture: design/architecture.md
      - Performance: design/performance.md
      - Extensibility: design/extensibility.md
      - Testing: design/testing.md
  - Release Notes: release_notes.md