/*
 * The GNU Lesser General Public License (LGPL)
 *
 * Copyright (c) 2025-2026 Jay Iuliano
 *
 * This file is part of Astrea.
 */

#include <gtest/gtest.h>

#include <cmath>
#include <filesystem>

#include <astro/astro.hpp>
#include <trace/trace.hpp>

using namespace astrea;
using namespace astro;
using namespace trace;

using mp_units::si::unit_symbols::deg;
using mp_units::si::unit_symbols::km;
using mp_units::si::unit_symbols::s;

class OutputTest : public testing::Test {
  public:
    // Short simulation: 5 timesteps at 1-min resolution over 4 minutes.
    Date startDate;
    Time resolution = 60.0 * s;
    Date endDate    = startDate + 4.0 * resolution;

    const std::filesystem::path dbPath = std::filesystem::temp_directory_path() / "trace_output_test.db";

    ViewerConstellation make_constellation()
    {
        ViewerConstellation constellation(startDate, 7000.0 * km, 53.0 * deg, 1, 1, 2.0);
        Integrator integrator;
        constellation.propagate(endDate, integrator);
        return constellation;
    }

    // Expected number of timesteps in the date vector generated by save_ground_track,
    // matching AccessAnalyzer::create_date_vector logic.
    std::size_t expected_n_dates() const
    {
        std::size_t n = 1;
        Time elapsed  = 0.0 * s;
        while (startDate + elapsed < endDate) {
            if (startDate + elapsed + resolution >= endDate) { elapsed = endDate - startDate; }
            else {
                elapsed += resolution;
            }
            ++n;
        }
        return n;
    }
};

int main(int argc, char** argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

TEST_F(OutputTest, DatabaseCreationDoesNotThrow) { ASSERT_NO_THROW(DatabaseOutputManager manager(dbPath, true)); }

TEST_F(OutputTest, SaveGroundTrackRecordCountMatchesSatelliteTimesteps)
{
    ViewerConstellation constellation = make_constellation();
    const std::size_t nSats           = constellation.size();
    const std::size_t nDates          = expected_n_dates();

    DatabaseOutputManager manager(dbPath, true);
    manager.save_ground_track(constellation, startDate, endDate, resolution);

    const auto records = manager.get_storage().get_all<GroundTrackRecord>();
    ASSERT_EQ(records.size(), nSats * nDates);
}

TEST_F(OutputTest, SaveGroundTrackLatitudesInValidRange)
{
    ViewerConstellation constellation = make_constellation();
    DatabaseOutputManager manager(dbPath, true);
    manager.save_ground_track(constellation, startDate, endDate, resolution);

    for (const auto& rec : manager.get_storage().get_all<GroundTrackRecord>()) {
        EXPECT_GE(rec.latitude, -90.0) << "latitude below -90 for sat " << rec.satellite;
        EXPECT_LE(rec.latitude, 90.0) << "latitude above 90 for sat " << rec.satellite;
    }
}

TEST_F(OutputTest, SaveGroundTrackLongitudesInValidRange)
{
    ViewerConstellation constellation = make_constellation();
    DatabaseOutputManager manager(dbPath, true);
    manager.save_ground_track(constellation, startDate, endDate, resolution);

    for (const auto& rec : manager.get_storage().get_all<GroundTrackRecord>()) {
        EXPECT_GE(rec.longitude, -180.0) << "longitude below -180 for sat " << rec.satellite;
        EXPECT_LE(rec.longitude, 180.0) << "longitude above 180 for sat " << rec.satellite;
    }
}

TEST_F(OutputTest, SaveGroundTrackTimeSecondsInRange)
{
    ViewerConstellation constellation = make_constellation();
    DatabaseOutputManager manager(dbPath, true);
    manager.save_ground_track(constellation, startDate, endDate, resolution);

    const double propTimeSec = (endDate - startDate).numerical_value_in(s);
    for (const auto& rec : manager.get_storage().get_all<GroundTrackRecord>()) {
        EXPECT_GE(rec.timeSec, 0.0);
        EXPECT_LE(rec.timeSec, propTimeSec);
    }
}

TEST_F(OutputTest, SaveGroundTrackFirstTimeIsZero)
{
    ViewerConstellation constellation = make_constellation();
    DatabaseOutputManager manager(dbPath, true);
    manager.save_ground_track(constellation, startDate, endDate, resolution);

    const auto records = manager.get_storage().get_all<GroundTrackRecord>();
    ASSERT_FALSE(records.empty());
    // At least one record must have timeSec == 0 (the start epoch).
    const bool hasZero =
        std::any_of(records.begin(), records.end(), [](const GroundTrackRecord& r) { return r.timeSec == 0.0; });
    EXPECT_TRUE(hasZero);
}

TEST_F(OutputTest, SaveGroundTrackSatelliteNamesNonEmpty)
{
    ViewerConstellation constellation = make_constellation();
    DatabaseOutputManager manager(dbPath, true);
    manager.save_ground_track(constellation, startDate, endDate, resolution);

    for (const auto& rec : manager.get_storage().get_all<GroundTrackRecord>()) {
        EXPECT_FALSE(rec.satellite.empty());
    }
}

TEST_F(OutputTest, SaveGroundTrackIsIdempotent)
{
    ViewerConstellation constellation = make_constellation();
    DatabaseOutputManager manager(dbPath, true);
    manager.save_ground_track(constellation, startDate, endDate, resolution);
    const std::size_t countFirst = manager.get_storage().get_all<GroundTrackRecord>().size();

    manager.save_ground_track(constellation, startDate, endDate, resolution);
    const std::size_t countSecond = manager.get_storage().get_all<GroundTrackRecord>().size();

    ASSERT_EQ(countFirst, countSecond);
}

TEST_F(OutputTest, ClearAllTablesRemovesGroundTrackRecords)
{
    ViewerConstellation constellation = make_constellation();
    DatabaseOutputManager manager(dbPath, true);
    manager.save_ground_track(constellation, startDate, endDate, resolution);
    ASSERT_GT(manager.get_storage().get_all<GroundTrackRecord>().size(), 0);

    manager.clear_all_tables();
    ASSERT_EQ(manager.get_storage().get_all<GroundTrackRecord>().size(), 0);
}
