from enum import IntEnum
import numpy as np
import pandas as pd
import os
import pathlib
import argparse

ASTRO_ROOT = pathlib.Path(
    os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), ".."))
)


def write_to_file(outPath: str, eopData: pd.DataFrame, rebuild: bool) -> None:
    """
    Format and write x, y, z position coefficients to file
    """

    # Common strings
    warningString = "//!!!!!!! WARNING: Autogenerated file, do not edit !!!!!!!\n"
    className = "EarthOrientationParameters"
    nEntries = eopData.shape[0]

    # Build output directory if it doesn't exist
    outDir = outPath
    os.makedirs(outDir, exist_ok=True)

    # Write header file
    header = f"{className}.hpp"
    headerfile = os.path.join(outPath, header)
    if os.path.exists(headerfile) and not rebuild:
        print(f" -- {headerfile} already exists, skipping rebuild...")
        return
    with open(headerfile, "w+") as fID:
        fID.write(warningString)

        fID.write(f"#pragma once\n\n")
        fID.write(f"#include <array>\n")
        fID.write(f"#include <mp-units/systems/si/prefixes.h>\n")
        fID.write(f"#include <units/units.hpp>\n")
        fID.write(f"#include <astro/time/Date.hpp>\n\n")
        fID.write(f"namespace astrea {{\n")
        fID.write(f"namespace astro {{\n")
        fID.write(f"namespace eop {{\n\n")
        fID.write(f"struct {className} {{\n")

        fID.write(f"\t{className}() = delete;\n")
        fID.write(f"\t~{className}() = delete;\n\n")

        # Build a struct for each line of the EOP data
        fID.write(f"\tstatic constexpr int N_PARAM = {nEntries};\n")
        fID.write(f"\tstruct EopRow {{\n")
        fID.write(f"\t\tDate MJD;\n")
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::arcsecond>> PMx;\n"
        )
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::arcsecond>> PMy;\n"
        )
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::second>> TAI_UT1;\n"
        )
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::arcsecond>> PMxSig;\n"
        )
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::arcsecond>> PMySig;\n"
        )
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::arcsecond>> UTSig;\n"
        )
        fID.write(f"\t\tmp_units::quantity<mp_units::one> PMxy;\n")
        fID.write(f"\t\tmp_units::quantity<mp_units::one> PMxUT;\n")
        fID.write(f"\t\tmp_units::quantity<mp_units::one> PMyUT;\n")
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::arcsecond>> DX;\n"
        )
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::arcsecond>> DY;\n"
        )
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::arcsecond>> DXSig;\n"
        )
        fID.write(
            f"\t\tmp_units::quantity<mp_units::si::milli<mp_units::si::arcsecond>> DYSig;\n"
        )
        fID.write(f"\t\tmp_units::quantity<mp_units::one> Corr_DxDy;\n")
        fID.write(f"\t}};\n\n")

        # data array
        fID.write(f"\tstatic const std::array<EopRow, {nEntries}> DATA;\n")

        fID.write("};\n\n")
        fID.write(f"}} // namespace eop \n\n")
        fID.write(f"}} // namespace astro \n")
        fID.write(f"}} // namespace astrea \n")

    # Write source file
    sourcefile = os.path.join(outPath, f"{className}.cpp")
    with open(sourcefile, "w+") as fID:
        fID.write(warningString)

        fID.write(f"#include <astro/eop/{header}>\n\n")
        fID.write(f"namespace astrea {{\n")
        fID.write(f"namespace astro {{\n")
        fID.write(f"namespace eop {{\n\n")

        fID.write(f"using namespace mp_units;\n")
        fID.write(f"using namespace mp_units::si;\n")

        # Write the x coefficients to file
        fID.write(
            f"const std::array<{className}::EopRow, {nEntries}> {className}::DATA {{\n"
        )
        for index, row in eopData.iterrows():
            fID.write(
                f"\tEopRow({{ Date(JulianDate(JulianDateClock::duration{{{2400000.5 + row['MJD (TAI)']}}})), "
            )
            fID.write(f"{row['PMx (mas)']} * milli<arcsecond>, ")
            fID.write(f"{row['PMy (mas)']} * milli<arcsecond>, ")
            fID.write(f"{row['TAI-UT1 (ms)']} * milli<second>, ")
            fID.write(f"{row['PMxSig (mas)']} * milli<arcsecond>, ")
            fID.write(f"{row['PMySig (mas)']} * milli<arcsecond>, ")
            fID.write(f"{row['UTSig (ms)']} * milli<arcsecond>, ")
            fID.write(f"{row['PMxy']} * one, ")
            fID.write(f"{row['PMxUT']} * one, ")
            fID.write(f"{row['PMyUT']} * one, ")
            fID.write(f"{row['DX (mas)']} * milli<arcsecond>, ")
            fID.write(f"{row['DY (mas)']} * milli<arcsecond>, ")
            fID.write(f"{row['DXSig (mas)']} * milli<arcsecond>, ")
            fID.write(f"{row['DYSig (mas)']} * milli<arcsecond>, ")
            fID.write(f"{row['Corr DxDy']} * one }})")
            if index < nEntries - 1:
                fID.write(",")
            fID.write("\n")
        fID.write(f"}};\n\n")

        fID.write(f"}} // namespace eop \n")
        fID.write(f"}} // namespace astro \n")
        fID.write(f"}} // namespace astrea \n")

    return


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate Earth Orientation Parameters files for Astrea"
    )
    parser.add_argument(
        "--infile",
        nargs="+",
        type=str,
        default=[
            os.path.join(ASTRO_ROOT, "data", "earth_orientation_parameters", "eop.long")
        ],
        help="List of celestial bodies to generate ephemeris files for. Default is all bodies.",
    )
    parser.add_argument("-o", "--output_path", type=str, default=None)
    parser.add_argument(
        "-r",
        "--rebuild",
        type=bool,
        default=False,
        help="Rebuild the ephemeris files even if they already exist. Default is False.",
    )
    args = parser.parse_args()

    if not args.infile:
        print("No input files provided. Exiting.")
        exit(1)

    if not args.output_path:
        print("No output path provided. Exiting.")
        exit(1)

    infile = args.infile[0]
    output_path = args.output_path
    rebuild = args.rebuild

    # Ensure the output directory exists
    os.makedirs(output_path, exist_ok=True)

    # Read the EOP data from the input file
    columns = [
        "MJD (TAI)",
        "PMx (mas)",
        "PMy (mas)",
        "TAI-UT1 (ms)",
        "PMxSig (mas)",
        "PMySig (mas)",
        "UTSig (ms)",
        "PMxy",
        "PMxUT",
        "PMyUT",
        "DX (mas)",
        "DY (mas)",
        "DXSig (mas)",
        "DYSig (mas)",
        "Corr DxDy",
    ]
    eopData = pd.read_csv(
        infile, header=None, skiprows=20, skipfooter=1, comment="$", engine="python"
    )
    eopData = eopData.iloc[:, : len(columns)]  # Keep only the first 15 columns
    eopData.columns = columns

    write_to_file(output_path, eopData, rebuild)
