# syntax=docker/dockerfile:1

FROM ubuntu:latest AS base

RUN apt-get update && \
    apt-get -y install \
    make \
    cmake

FROM base AS final

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -y install \
    gdb \
    bash-completion \
    mono-mcs \
    curl \
    clang-format \
    libsqlite3-dev \
    libssl-dev \
    libgl1-mesa-dev \
    xorg-dev \
    python3 \
    python3-venv \
    git \
    gnuplot \
    software-properties-common \
    ninja-build \
    && \
    add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get -y install gcc-15 g++-15 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 100 && \
    rm -rf /var/lib/apt/lists/*

# Create a non-root user
ARG USER=user
RUN useradd -ms /bin/bash $USER

# Change ownership of home directory to the non-root user
ENV USER_HOME=/home/$USER
RUN chown -R $USER:$USER $USER_HOME

# Switch to user
USER $USER
WORKDIR $USER_HOME

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="$USER_HOME/.local/bin:$PATH"

# Install gcovr using uv
RUN uv tool install gcovr
