# Copyright (c) 2025 Jay Iuliano
#
# This file is part of Astrea.
# Astrea is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# Astrea is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should
# have received a copy of the GNU General Public License along with Astrea. If not, see <https://www.gnu.org/licenses/>.

# ---- Conan-managed packages ----
# These are installed via `conan install` before the cmake configure step.
# The conan_toolchain.cmake generated by Conan sets CMAKE_PREFIX_PATH so
# find_package can locate them.
find_package(mp-units REQUIRED)
find_package(nlohmann_json REQUIRED)
find_package(SQLite3 REQUIRED)
find_package(cpr REQUIRED)

# gsl-lite is a transitive dep of mp-units; keep this define for compatibility
add_compile_definitions(gsl_FEATURE_GSL_COMPATIBILITY_MODE=1)

# ---- CPM-managed packages (not available in ConanCenter) ----
include(cmake/CPM.cmake)

# SQLite ORM - header-only wrapper around SQLite3, not in ConanCenter
CPMFindPackage(
    NAME sqlite_orm
    GITHUB_REPOSITORY fnc12/sqlite_orm
    GIT_TAG v1.9.1
    GIT_SHALLOW TRUE
    SYSTEM YES
)

# Matplot++ for plotting - not in ConanCenter
CPMFindPackage(
    NAME matplotplusplus
    GITHUB_REPOSITORY alandefreitas/matplotplusplus
    GIT_TAG v1.2.2
    GIT_SHALLOW TRUE
    OPTIONS
    "MATPLOTPP_BUILD_EXAMPLES OFF"
    "MATPLOTPP_BUILD_SHARED_LIBS ON"
    "MATPLOTPP_BUILD_TESTS OFF"
    "BUILD_SHARED_LIBS ON"
)
if(DEFINED matplotplusplus_SOURCE_DIR)
    install(DIRECTORY "${matplotplusplus_SOURCE_DIR}/source/matplot" DESTINATION include)
endif()

# gtl (fast hash maps) - header-only, not in ConanCenter
CPMFindPackage(
    NAME gtl
    GITHUB_REPOSITORY greg7mdp/gtl
    GIT_SHALLOW TRUE
    GIT_TAG v1.2.0
)
if(DEFINED gtl_SOURCE_DIR)
    install(DIRECTORY "${gtl_SOURCE_DIR}/include/" DESTINATION include)
endif()

# ---- Conan-managed test/benchmark packages ----
if(${BUILD_TESTS})
    find_package(GTest REQUIRED)
    set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
    include(GoogleTest)
    enable_testing()
endif()

if(${BUILD_BENCHMARKS})
    find_package(benchmark REQUIRED)
endif()