#
# The GNU Lesser General Public License (LGPL)
#
# Copyright (c) 2025 Jay Iuliano
#
# This file is part of Astrea.
# Astrea is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# Astrea is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should
# have received a copy of the GNU General Public License along with Astrea. If not, see <https://www.gnu.org/licenses/>.
#

name: Bump Version

permissions: write-all

on:
  push:
    branches: [ "dev" ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iulianojay/astrea:dev
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Mark repository as safe
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Fetch tags
      run: git fetch --prune --unshallow --tags

    - name: Increment Version
      run: |
        sh ./scripts/increment_version.sh
