name: Delete old container images

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: astrea
          cut-off: One month ago UTC
          keep-at-least: 1
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token