#
# The GNU Lesser General Public License (LGPL)
#
# Copyright (c) 2025 Jay Iuliano
#
# This file is part of Astrea.
# Astrea is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# Astrea is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should
# have received a copy of the GNU General Public License along with Astrea. If not, see <https://www.gnu.org/licenses/>.
#

name: Delete old container images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: astrea
          cut-off: One month ago UTC
          keep-at-least: 1
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token